version: '3.6'
services:

  wordpress:
    image: wordpress:php7.3-fpm
    container_name: wordpress
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wordpress:/var/www/html/healthlifevn_src
    environment:
      - WORDPRESS_DB_NAME=healthlifevn_db
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=mysql:3306
      - WORDPRESS_DB_USER=healthlifevn_usr
      - WORDPRESS_DB_PASSWORD=healthlifevn@Pass
    depends_on:
      - mysql
    restart: always

  mysql:
    image: mariadb:latest
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Dep@rtment
      - MYSQL_USER=healthlifevn_usr
      - MYSQL_PASSWORD=healthlifevn@Pass
      - MYSQL_DATABASE=healthlifevn_db
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/healthlifevn.conf:/etc/nginx/conf.d/healthlifevn.conf
      - ./logs/nginx:/var/log/nginx
      - ./wordpress:/var/www/html/healthlifevn_src
      #- ./certs:/etc/letsencrypt
      #- ./certs-data:/data/letsencrypt
    depends_on:
      - wordpress
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - 3333:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Dep@rtment

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    links:
      - mysql
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: net_app
